### ISSUE TITLE
Confusing parameter name

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#12]
In this action method, a parameter of type ComputerCreationDTO is being supplied, named as ComputerDTO. However, ComputerDTO is another type, and this name could easily be confused with the wrong type. For example, in the return statement, we are mapping computer onto ComputerDTO, and I was actually confused as to why I was doing this, when I already had the ComputerDTO argument. I then later realized that ComputerDTO argument was of type ComputerCreationDTO, and not ComputerDTO.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-API/Controllers/ComputersController.cs#L78-L88

**Comment by LidiaIvanova** [comment]
0,2
