### ISSUE TITLE
Wrong parameter name

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#15]
Parameter name is issueDTO, but IssueDTO is another type, and can be confused. Change it to something like issueCreationDTO.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-API/Controllers/IssuesController.cs#L59

**Comment by LidiaIvanova** [comment]
0,2
