### ISSUE TITLE
Extra if statement

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#17]
We could just use one if statement with an OR operator. This reduces repetition of code, makes it more readable, and reduces lines in the method.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/IssuesController.cs#L23-L26

**Comment by LidiaIvanova** [comment]
It's conditional complexity.
0,5
