### ISSUE TITLE
Long method / violation of single responsibility principle

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#18]
Long methods are hard to read, and they usually fulfill more than a single responsibility. Such methods should be dealt with using the Extract method, where different functionalities are moved to their own methods.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/IssuesController.cs#L21-L81

**Comment by LidiaIvanova** [comment]
0,5
