### ISSUE TITLE
Long Parameter list

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#19]
It’s hard to understand long list of parameters, which become contradictory and hard to use as they grow longer. It is better to "Introduce a Parameter object".

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/IssuesController.cs#L21

**Comment by LidiaIvanova** [comment]
0,2
