### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#20]
Move code to it's own method using the Extract Method.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/IssuesController.cs#L60-L79

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/IssuesController.cs#L104-L123

**Comment by LidiaIvanova** [comment]
Why is this code bad? What principles does it violate? What can the existence of such code lead to? 0,3
