### ISSUE TITLE
Invalid variable name

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#23]
It's unclear what obj means here. Better to rename it to a more meaningful name.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/LabController.cs#L100-L106

**Comment by LidiaIvanova** [comment]
0,2
