### ISSUE TITLE
Move method

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#24]
The DeleteComputer method logically does not belong in the LabsController. It is better to move it to it's own ComputerController using the Move method.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/LabController.cs#L156-L172

**Comment by LidiaIvanova** [comment]
0,2
