### ISSUE TITLE
Long line of code

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#25]
Long lines of code can make code harder to read and understand, and can also make it more difficult to maintain and modify in the future. 

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/LabController.cs#L160

**Comment by LidiaIvanova** [comment]
0,1
