### ISSUE TITLE
Dependency pruning.

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#29]
Pruning unused dependencies is important because it can help to reduce the size of the codebase, make it easier to understand and navigate, and improve the performance of the code by reducing the amount of unnecessary overhead. Unused dependencies can also introduce security vulnerabilities and increase the risk of conflicts and errors in the code.

There are unused javascript libraries (uuid, jquery-validation, jquery-validation-unobtrusive) in the following location:

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/tree/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/wwwroot/lib

**Comment by LidiaIvanova** [comment]
0,5
