### ISSUE TITLE
Duplicate shared views between Admin and User Areas

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#3]
In my case, I have to edit layout files twice just for the views to change for both admin and user. It is repetitive and tiring. It doesn't scale, as the program gets bigger, I'll have to spend more time trying to figure out the same thing in two different places.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/tree/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Views/Shared

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/tree/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/User/Views/Shared

**Comment by LidiaIvanova** [comment]
0,5
