### ISSUE TITLE
Anaemic domain models.

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#30]
The anemic domain model is described as a programming anti-pattern where the domain objects contain little or no business logic like validations, calculations, rules, and so forth. The business logic is thus baked into the architecture of the program itself, making refactoring and maintenance more difficult and time-consuming.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/tree/13fd912b300904b6ff8bfb51da2be73ad1126bca/ModelsLibrary/Models

**Comment by LidiaIvanova** [comment]
0,5
