### ISSUE TITLE
Implement ActionFilters to execute some common functionality before or after an action is run (in both API and MVC)

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#4]
All action methods, in most of the controllers, have some common checks they make before moving to the business logic. It's better to enclose these checks in action filters, and apply these filters to the controller.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-API/Controllers/ComputersController.cs#L34-L45

**Comment by LidiaIvanova** [comment]
Is it the duplicate code? Or what?

**Comment by yahya-abdul-majeed** [comment]
> Is it the duplicate code? Or what?

@LidiaIvanova Yes, it removes common checks in actions.
