### ISSUE TITLE
Replace HttpClient with IHttpClientFactory, and add as a dependency injection.

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#5]
I have been using the HttpClient class to make http requests. The problem is that I am initiating a new instance for each action method, providing the same baseUrl and authorization headers everywhere. Also, the microsoft documentation states the following about the HttpClient class, and suggests to use the IHttpClientFactory.
_

> Though this class implements IDisposable, declaring and instantiating it within a using statement is not preferred because when the HttpClient object gets disposed of, the underlying socket is not immediately released, which can lead to a socket exhaustion problem.

_
https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/IssuesController.cs#L28-L35

**Comment by LidiaIvanova** [comment]
0,3
