### ISSUE TITLE
Useless comments

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#6]
Leaving comments in code with no context or meaning can often times confuse other readers, or yourself, if you return to the code after a while. In this example, these comments have no meaning, or use, for them to exist within this method.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-Web/Areas/Admin/Controllers/IssuesController.cs#L130-L132

**Comment by LidiaIvanova** [comment]
0,2
