### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#7]
In the AuthController class, I have two dependency injections which I haven't used, and added them thinking I would use them at some point.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-API/Controllers/AuthController.cs#L15

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-API/Controllers/AuthController.cs#L13

**Comment by LidiaIvanova** [comment]
Why is this code bad? What principles does it violate? What can the existence of such code lead to?
0,3
