### ISSUE TITLE
Unnecessary if statement

### ISSUE THREAD

**Issue by yahya-abdul-majeed** [yahya-abdul-majeed/CodeRefactoring2023#8]
This if statement is useless as user is nullable, and if user is null, the next if statement will be false, and the else part would be executed.

https://github.com/yahya-abdul-majeed/CodeRefactoring2023/blob/13fd912b300904b6ff8bfb51da2be73ad1126bca/CLabManager-API/Controllers/AuthController.cs#L33-L36

**Comment by LidiaIvanova** [comment]
Why is this code bad? What principles does it violate? What can the existence of such code lead to?
0,1
